// Auto-generated by scripts/inject_build_info.sh — do not edit.
enum BuildInfo {
    static let gitBranch = "claude/recursing-beaver-b3ebd9"
    static let gitCommit = "8f6a1e9-dirty"
    static let buildTimestamp = "2026-04-24T20:26:49Z"
}
