// Auto-generated by scripts/inject_build_info.sh — do not edit.
enum BuildInfo {
    static let gitBranch = "claude/recursing-beaver-b3ebd9"
    static let gitCommit = "c283d94"
    static let buildTimestamp = "2026-04-25T00:31:01Z"
}
