// Auto-generated by scripts/inject_build_info.sh — do not edit.
enum BuildInfo {
    static let gitBranch = "claude/recursing-beaver-b3ebd9"
    static let gitCommit = "2b63a94-dirty"
    static let buildTimestamp = "2026-04-24T19:17:16Z"
}
