#!/bin/bash
set -e
# Generates GlycoTrack/Config/BuildInfo.generated.swift with git branch, commit, timestamp.
# Run before xcodegen / xcodebuild so the generated file is compiled into the app.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DIRTY=$(git diff --quiet 2>/dev/null && echo "" || echo "-dirty")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

OUT="GlycoTrack/Config/BuildInfo.generated.swift"
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// Auto-generated by scripts/inject_build_info.sh — do not edit.
enum BuildInfo {
    static let gitBranch = "$BRANCH"
    static let gitCommit = "$COMMIT$DIRTY"
    static let buildTimestamp = "$TIMESTAMP"
}
EOF
echo "Wrote $OUT (branch=$BRANCH commit=$COMMIT$DIRTY)"
